# Generated by Django 4.0 on 2024-05-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Currency',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('GBP', 'Gbp'), ('INR', 'Inr'), ('MAD', 'Mad')], max_length=3, null=True),
        ),
    ]
